<?php
define('ACCOUNT_TYPE_USER', 0);
define('ACCOUNT_TYPE_CUSTOMER', 1);
define('ACCOUNT_TYPE_MANAGER', 2);
define('ACCOUNT_TYPE_ADMIN', 3);
define('DEFAULT_LANGUAGE', 'en-us');
define('NO_IMAGE_URL', 'NoIMG');
define('EMAIL_DEFAULT', 'noreply@gmail.com');

define('ITEMS_PER_PAGE', 10);

//define api
define('API_SUCCESS', 1);
define('API_ERROR', 0);

define('ORDER_BUY', 0);
define('WAITTING_APPROVE', 1);
define('SUCCESS_BUY', 2);
define('CANCEL_BUY', 3);